services:
  ctfd:
    image: ctfd/ctfd:latest
    ports:
      - "80:8000"

  web2:
    build: ./challs/web/yourAPI/site
    ports:
      - "8002:80"
    volumes:
      - ./challs/web/yourAPI/site/files:/var/www/html/files
      - ./challs/web/yourAPI/site/index.php:/var/www/html/index.php
      - ./challs/web/yourAPI/site/.env:/var/www/html/.env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html


  misc1:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10010:1337'
    volumes:
      - './challs/misc/stampante/src.py:/home/user/chall.py:ro'
      - './challs/misc/stampante/art.txt:/home/user/art.txt:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{f4sTes7_Pr1nT3r_3V3r_cR34T3d}'
      
      - 'TIMEOUT=120'    
      - 'FORWARD_STDERR=true'


  misc3:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10020:1337'
    volumes:
      - './challs/misc/calc1/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{aaaaa}'
      
      - 'TIMEOUT=120'    
      - 'LOG_STDERR=true'

  misc4:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true

    ports:
      - '10030:1337'
    volumes:
      - './challs/misc/calc2/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{asdsad}'
      
      - 'TIMEOUT=120'    
      - 'LOG_STDERR=true'