services:
  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rossictfdb
      MYSQL_USER: rossictf
      MYSQL_PASSWORD: rossictf
    volumes:
      - mysql_data:/var/lib/mysql

  ctfd:
    image: ctfd/ctfd:latest
    environment:
      DATABASE_URL: mysql+pymysql://rossictf:rossictf@mysql/rossictfdb
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  # web1
  ssl:
    build: ./challs/web/ssl/src
    ports:
      - "8001:80"
    volumes:
      - ./challs/web/ssl/src/index.php:/var/www/html/index.php
      - ./challs/web/ssl/src/logout.php:/var/www/html/logout.php
      - ./challs/web/ssl/src/V5jPCZdP.php:/var/www/html/V5jPCZdP.php
      - ./challs/web/ssl/src/welcome.php:/var/www/html/welcome.php
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  # web2
  yourapi:
    build: ./challs/web/yourAPI/src
    ports:
      - "8002:80"
    volumes:
      - ./challs/web/yourAPI/src/files:/var/www/files
      - ./challs/web/yourAPI/src/index.php:/var/www/html/index.php
      - ./challs/web/yourAPI/src/.env:/var/www/.env
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  # web3
  # evilrandom:
  #   build: ./challs/web/evilrandom/site
  #   ports:
  #     - "8003:8000"


  # ytrecommend:
  #   build: ./challs/web/ytrecommender/site
  #   ports:
  #     - "8004:4567"
  #   environment:
  #     'FLAG=rossiCTF{CHANGEME}'
  #   restart: unless-stopped

  # misc1
  stampante:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10010:1337'
    volumes:
      - './challs/misc/stampante/src/src.py:/home/user/chall.py:ro'
      - './challs/misc/stampante/src/art.txt:/home/user/art.txt:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{f4sTes7_Pr1nT3r_3V3r_cR34T3d!_be7a68}'
      - 'TIMEOUT=120'
      - 'FORWARD_STDERR=true'

  # misc3
  calc1:
    build: ./challs/misc/calc1/src
    restart: unless-stopped
    init: true
    privileged: true
    ports:
      - '10020:1337'
    volumes:
      - './challs/misc/calc1/src/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{5yMpy_1S_0v3rP0w3reD_3v4l_iS_7o0!_f6b8a1}'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

  # misc4
  calc2:
    image: cybersecnatlab/challenge-jail:python-3.12-alpine@sha256:4ca713d2836422b58d457829e28bf1883bb5a2eb5ba122bc8b77a919b41859aa
    restart: unless-stopped
    init: true
    privileged: true

    ports:
      - '10030:1337'
    volumes:
      - './challs/misc/calc2/src/src.py:/home/user/chall.py:ro'

    command: ["/usr/local/bin/python3", "/home/user/chall.py"]

    environment:
      - 'FLAG=rossiCTF{dUnD3r5_4r3_7h3_N3w_M47h!1!_de87b2}'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

  # binary2
  pswgenerator:
    image: cybersecnatlab/challenge-jail:ubuntu-focal@sha256:5a527a362177415e717aa3d8bad646513ebd648da1f72fe012639176e228884f
    restart: unless-stopped
    init: true
    privileged: true

    ports:
      - '20010:1337'
    volumes:
      - './challs/binary/pswgenerator/attachments/pswgenerator:/home/user/chall:ro'

    environment:
      - 'FLAG=rossiCTF{4pP4r3N7ly_th3_p4Ssw0rD_W45n7_s0_54f3..._a3f9c1}'
      - 'TIMEOUT=120'
      - 'LOG_STDERR=true'

volumes:
  mysql_data: